---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-api-app-keys
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-role: vault
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/mutate-configmap: "true"
  labels:
    helm.sh/chart: {{ include "keda.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- end }}
data:
  api-key: {{ .Values.keda.datadog.apiKey | b64enc }}
  app-key: {{ .Values.keda.datadog.appKey | b64enc }}
type: Opaque
