---
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: datadog
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-failed
  labels:
    helm.sh/chart: {{ include "keda.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- end }}
spec:
  hashiCorpVault:
    address: "https://vault.vault:8200"
    authentication: kubernetes
    role: vault
    credential:
      serviceAccount: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    secrets:
    - parameter: apiKey
      key: api-key
      path: "secret/data/datadog"
    - parameter: appKey
      key: app-key
      path: "secret/data/datadog"