# Global values for KEDA
keda:
  crds:
    install: true

  logging:
    format: json
  
  resources:
    operator:
      limits:
        cpu: 1
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 100Mi
    metricServer:
      limits:
        cpu: 1
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 100Mi

  prometheus:
    metricServer:
      enabled: true
    operator:
      enabled: true

  podAnnotations:
    keda:
      ad.datadoghq.com/keda-operator.logs: '[{"source": "go", "service": "keda-operator", "sourcecategory": "kubernetes"}]'
    metricsAdapter:
      ad.datadoghq.com/keda-operator-metrics-apiserver.logs: '[{"source": "go", "service": "keda-operator-metrics-apiserver", "sourcecategory": "kubernetes"}]'

datadog:
  apiKey: "vault:secret/data/datadog#api-key"
  appKey: "vault:secret/data/datadog#app-key"
